name: flutter_smbud
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/food.jpg
    - assets/images/mongo.png
    - assets/images/neo.png
    - assets/images/work.png
    - assets/images/dataset/carrer.png
    - assets/images/dataset/food.png
    - assets/images/dataset/food2.png
    - assets/images/dataset/carrer2.png
    - assets/images/dataset/es_node.png
    - assets/images/QN/QN1.png
    - assets/images/QN/QN2.png
    - assets/images/QN/QN3.png
    - assets/images/QN/QN4.png
    - assets/images/QN/QN5.png
    - assets/images/QN/QN6.png
    - assets/images/QN/QN7.png
    - assets/images/QN/QN8.png
    - assets/images/QN/QN9.png
    - assets/images/QN/QN10.png


  fonts:
      - family: MyFont
        fonts:
          - asset: assets/fonts/chinese.msyh.ttf
